require 'capistrano/setup'
require 'capistrano/deploy'
require 'capistrano/rails'
require 'capistrano/passenger'
require 'capistrano/npm'
require 'capistrano/touch-linked-files'
require 'whenever/capistrano'
require 'slackistrano/capistrano'
