gem "bundler", ">= 1.7.0"

source 'https://rubygems.org' do
  # Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
  gem 'rails', '4.0.0'

  # Use SCSS for stylesheets
  gem 'sass-rails', '5.0.0.beta1'

  # Use Uglifier as compressor for JavaScript assets
  gem 'uglifier', '>= 1.3.0'

  # Use CoffeeScript for .js.coffee assets and views
  gem 'coffee-rails', '~> 4.0.0'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', platforms: :ruby

  # Use jquery as the JavaScript library
  gem 'jquery-rails'
end

source 'http://localhost:3000' do
  # source 'https://rails-assets.org'
  gem "rails-assets-sugar"
  gem "rails-assets-angular"
end
